### ISSUE TITLE
Does not build behind a proxy

### ISSUE THREAD

**Issue by mlenormand** [derekhulley/alfresco-benchmark#39]
Alfresco Benchmark doesn't work behind a proxy : 

Could not open inputStream for http://downloads.mongodb.org/win32/mongodb-win
32-x86_64-2008plus-2.6.1.zip

Java-configured or Maven-configured proxies are not taken into account.

The project flapdoodle-oss/de.flapdoodle.embed.mongo recently gives a solution to customize a proxy for download :

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-proxy-for-download

Could it be possible to add this feature to the project ? Or at least provide me with a workaround ?

Thanks in advance.

**Comment by derekhulley** [comment]
This issue would prevent the successful execution of tests during
  mvn clean install
but is not a requirement for the execution in production.
I'd happily take a pull request, of course, as I have not looked at it yet myself.

A workaround might be to download and store the MongoDB zip locally by hand.
On my machine, the latest version uses path:
*C:\\Users\xxx\\.embedmongo\\win32\\mongodb-win32-x86_64-2008plus-2.6.1.zip*
Of course, the file you will need will be determined by your OS, etc.  If you try it out on an equivalent machine, then you can see what it downloads and where it stores it.

**Comment by derekhulley** [comment]
Actually, I see it says what it's trying to download :-)

**Comment by derekhulley** [comment]
Workaround is OK.  I've unplugged my laptop from the network and it still builds, provided the zip file is in the correct location:
<pre>
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.alfresco.bm.session.SessionServiceTest
Extract C:\Users\xxx\.embedmongo\win32\mongodb-win32-x86_64-2008plus-2.6.1.zip START
Extract C:\Users\xxx\.embedmongo\win32\mongodb-win32-x86_64-2008plus-2.6.1.zip DONE
[mongod output]note: noprealloc may hurt performance in many applications
</pre>
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.alfresco.bm.session.SessionServiceTest
Extract C:\Users\xxx\.embedmongo\win32\mongodb-win32-x86_64-2008plus-2.6.1.zip START
Extract C:\Users\xxx\.embedmongo\win32\mongodb-win32-x86_64-2008plus-2.6.1.zip DONE
[mongod output]note: noprealloc may hurt performance in many applications
</pre>

**Comment by derekhulley** [comment]
Our build environment uses this location:
>	Extract /var/lib/bamboo-agent/.embedmongo/linux/mongodb-linux-x86_64-2.6.1.tgz START
