### ISSUE TITLE
Property editor filter shows all properties in test run

### ISSUE THREAD

**Issue by derekhulley** [derekhulley/alfresco-benchmark#40]
Create a test and edit properties.
Use the properties editor filter and note that only filtered properties are displayed.

Create a test run and edit test run's properties.
Use the filter.
ALL properties are shown.

**Comment by paulbrodner** [comment]
Issue tested & fixed on [pull request 41](https://github.com/derekhulley/alfresco-benchmark/pull/41)
The filtering option is now available on both properties.html files (run/test)
