### ISSUE TITLE
Active tests filter show duplicates when multiple drivers are active

### ISSUE THREAD

**Issue by derekhulley** [derekhulley/alfresco-benchmark#47]
Steps:
* Run multiple of the same driver against a common configuration database.
* Create a new test.
* Select "Active Only".

Actual:
* An entry is shown for each test.

Expected:
* Only one entry per active test definition

Possible:
* One entry per test definition with a count after showing the number of drivers e.g.<br/>
<strong>cmis-1.0:6  (2 drivers)</strong>

**Comment by derekhulley** [comment]
![benchmark-no 47](https://cloud.githubusercontent.com/assets/5584103/6845515/6e78df68-d3ad-11e4-9381-cb33fad29b84.png)

**Comment by paulbrodner** [comment]
One entry per test definition is displayed now for **active tests**: ![active tests](http://s27.postimg.org/eiu95p1k3/Screen_Shot_2015_03_26_at_18_41_51.png)

**Comment by derekhulley** [comment]
Nice.  Thanks.
